CREATE TABLE Users (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Email NVARCHAR(100) UNIQUE NOT NULL,
    Password NVARCHAR(255) NOT NULL,
    Salt NVARCHAR(50) NOT NULL,
    LoginCount INT DEFAULT 0,
    CreateDate DATETIME DEFAULT GETDATE(),
    UpdateDate DATETIME DEFAULT GETDATE(),
    Active BIT DEFAULT 1
);
GO

CREATE TABLE Tasks (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Name NVARCHAR(100) NOT NULL,
    Description NVARCHAR(255) NULL,
    Status NVARCHAR(20) DEFAULT 'Pending',
    ParentId INT NULL,
    FOREIGN KEY (ParentId) REFERENCES Tasks(Id)
);
GO

CREATE TABLE UserTasks (
    Id INT PRIMARY KEY IDENTITY(1,1),
    UserId INT NOT NULL,
    TaskId INT NOT NULL,
    FOREIGN KEY (UserId) REFERENCES Users(Id),
    FOREIGN KEY (TaskId) REFERENCES Tasks(Id)
);
GO

CREATE TABLE TasksMedia (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Type NVARCHAR(50) NOT NULL,
    Path NVARCHAR(255) NOT NULL,
    TaskId INT NOT NULL,
    FOREIGN KEY (TaskId) REFERENCES Tasks(Id)
);